name: parked_player
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  flutter_inappwebview: ^6.1.5
  webview_flutter_android: ^4.10.11
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  jovial_svg: ^1.1.28
  reorderable_grid_view: ^2.2.8
  url_launcher: ^6.3.1
  http: ^1.6.0
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/parked_player.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
